### PR TITLE
Fixing of wrong OnHMIStatus expectation after streaming end 

### LINKED ISSUE #2404: Wrong OnHMIStatus expectation in 025_Media_app_must_get_ATTENUATED_streaming_state_when_navi_app_starts_streaming.lua
The wrong expectation in https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/a2040dbff1bc43b4008a71b6e6c1c58fc0dd93fa/test_scripts/MobileProjection/Phase2/025_Media_app_must_get_ATTENUATED_streaming_state_when_navi_app_starts_streaming.lua#L58

The first app should expect the changing of `audioStreamingState` back to `AUDIBLE` state, and the second app should expect 0 OnHMIlevel notification.

### PR DESCRIPTION
**Pull request by GetmanetsIrina**
Update to fix #2404 

This PR is **[ready]** for review.

### Summary
The first app should expect the changing of audioStreamingState back to `AUDIBLE` state, and the second app should expect 0 OnHMIlevel notification.

### ATF version
develop

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: test_scripts/MobileProjection/Phase2/025_Media_app_must_get_ATTENUATED_streaming_state_when_navi_app_starts_streaming.lua [hunk 1]
```diff
@@ -73,7 +76,7 @@ runner.Step("Set App Config", common.setAppConfig, { 1, "MEDIA", true })
 runner.Step("Register " .. appHMIType[1] .. " App", common.registerApp, { 1 })
 runner.Step("Activate App1, audioState:" .. "AUDIBLE", activateApp, { 1, 001, "AUDIBLE", "App1" })
 
-runner.Step("App starts Audio streaming", appStartAudioStreaming, {1, 2})
+runner.Step("App starts Audio streaming", appStartAudioStreaming, { 1, 2 })
```
Comment (dboltovskyi) [inline test_scripts/MobileProjection/Phase2/025_Media_app_must_get_ATTENUATED_streaming_state_when_navi_app_starts_streaming.lua:77]: @GetmanetsIrina Script needs to be added to `mobile_projection_2.txt` test set

**Comment by dboltovskyi** [comment]
@GetmanetsIrina Please notice all comments processed in f65304a5df870cf77d2cb5c1f086338fd08c16a9 and PR is marked as ready for review
