### PR TITLE
Fix scripts for defects according to 3279

### LINKED ISSUE #2376: Failed 2446, 2670_4 scripts after the merge of 3279 fix
Failed [2446](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/5_0/2446_SDL_doesn_t_resume_HMILevel_when_DEACTIVATE_HMI_with_isActive_is_true_then_false.lua), [2670_4](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/5_0/2670_4_GetInteriorVD_after_ignition_off.lua) scripts after the merge of #[3279](https://github.com/SmartDeviceLink/sdl_core/issues/3279) fix

Scripts: develop
ATF: develop
SDL: https://github.com/smartdevicelink/sdl_core/tree/release/6.1.0

### PR DESCRIPTION
**Pull request by GetmanetsIrina**
ATF Test Scripts to fix #2376 

This PR is **ready** for review.

### Summary
Updates in scripts related to the fix of [#3279](https://github.com/SmartDeviceLink/sdl_core/issues/3279)

### ATF version
develop

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: test_scripts/Defects/5_0/2670_4_GetInteriorVD_after_ignition_off.lua [hunk 1]
```diff
@@ -78,7 +77,7 @@ runner.Step("GetInteriorVehicleData RADIO", commonRC.rpcDenied,
   { "RADIO", 1, "GetInteriorVehicleData", "DISALLOWED" })
 runner.Step("ignitionOff", ignitionOff)
 runner.Step("Start SDL, HMI, connect Mobile, start Session", actions.start)
-runner.Step("RAI", actions.registerApp)
+runner.Step("RAI", actions.registerAppWOPTU)
```
Comment (jacobkeeler) [inline test_scripts/Defects/5_0/2670_4_GetInteriorVD_after_ignition_off.lua:80]: Is there a reason that a PTU is not started the first time this app is registered? It seems like it would meet the "new application" trigger.

Comment (dboltovskyi) [reply test_scripts/Defects/5_0/2670_4_GetInteriorVD_after_ignition_off.lua:80]: @jacobkeeler That's right PTU should be started. However it will be a new ignition cycle trigger (not a new application).
Actually this application was registered in a previous ignition cycle and PTU was not finished, so SDL should re-start PTU in a new ignition cycle. One additional point here - presence of application is not required due to HMI PTU feature. So PTU will be started once HMI initialized and before app re-registration.

File: test_scripts/Defects/5_0/2670_4_GetInteriorVD_after_ignition_off.lua [hunk 2]
```diff
@@ -43,8 +42,8 @@ local function updatePreloadedPT()
   utils.tableToJsonFile(preloadedTable, preloadedFile)
 end
 
-function preconditions()
```
Comment (jacobkeeler) [inline test_scripts/Defects/5_0/2670_4_GetInteriorVD_after_ignition_off.lua:46]: Seems that this test corrupts the preloaded policy table, it is not restored after completion

Comment (dboltovskyi) [reply test_scripts/Defects/5_0/2670_4_GetInteriorVD_after_ignition_off.lua:46]: @jacobkeeler Good catch. 
We didn't find this since we use external script runner on CI which performs additional backup/restore of SDL source files. 
Please find update in a520d88.
